services:
  - type: web
    name: chatbot-clinica-backend
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      # PORT: Render fornece automaticamente em process.env.PORT; não fixe valor
      - key: CORS_ORIGINS
        sync: false
      - key: ZAPI_INSTANCE_ID
        sync: false
      - key: ZAPI_TOKEN
        sync: false
      - key: ZAPI_CLIENT_TOKEN
        sync: false
      - key: GESTAODS_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: DASHBOARD_API_KEY
        sync: false
      - key: LOG_MESSAGES
        value: key

